# Generated by Django 4.2.3 on 2023-08-01 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Product",),
    ]
