# Generated by Django 4.2.3 on 2023-08-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbreviation", models.CharField()),
                ("alt_color", models.CharField()),
                ("classification", models.CharField()),
                ("color", models.CharField()),
                ("conference", models.CharField()),
                ("city", models.CharField()),
                ("mascot", models.CharField()),
                ("school", models.CharField()),
                ("logos", models.JSONField()),
                ("twitter", models.CharField()),
            ],
        ),
    ]
