# Generated by Django 4.2.3 on 2023-08-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cfbdata", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team", name="alt_color", field=models.CharField(null=True),
        ),
    ]
