# Generated by Django 4.2.3 on 2023-08-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cfbdata", "0002_alter_team_alt_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team", name="abbreviation", field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="team", name="city", field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="team", name="classification", field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="team", name="color", field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="team", name="logos", field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="team", name="mascot", field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="team", name="twitter", field=models.CharField(null=True),
        ),
    ]
