# Generated by Django 4.2.3 on 2023-08-12 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cfbdata", "0010_alter_prediction_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeismanFinalists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_1", models.CharField(blank=True, max_length=100, null=True)),
                ("player_2", models.CharField(blank=True, max_length=100, null=True)),
                ("player_3", models.CharField(blank=True, max_length=100, null=True)),
                ("player_4", models.CharField(blank=True, max_length=100, null=True)),
                ("player_5", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
